### ISSUE TITLE
How to use the scheduler from bundle osgi.enroute.scheduler.simple.provider correctly

### ISSUE THREAD

**Issue by ghenzler** [osgi/v2archive.osgi.enroute#11]
I'd like to use the scheduler from osgi.enroute.scheduler.simple.provider (for its ability to parse cron expressions and for it being a lot smaller than quartz) and now I'm wondering on how to do this the best since I need a minimal setup (so using the api bundle `osgi.enroute.base.api` is not desired). After checking `osgi.enroute` and this repo, this repo seems to contain the latest code. Although it has not changed for two years, it seems to have been pushed to maven central Jan 6th 2020 (but with group id `biz.aQute`). 

So what would be the idea on how to use this in OSGi context? Using `Conditional-Package` to avoid the unnecessary packages in `osgi.enroute.base.api`? Or is it just meant as "example" that can be copied elsewhere where needed? (searching for CronAdjuster finds some copies of it, e.g. [1])

[1] https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core/src/main/java/org/openhab/core/internal/scheduler/CronAdjuster.java

**Comment by pkriens** [comment]
I moved the code to [aQute-os](https://github.com/aQute-os/v2Archive.osgi.enroute) so I can have full control. When bugs are reported I will fix it there.

You can just use the binaries from Maven Central. If you do not want to use the binary on your  build path (the API is in the bundle), I can make standalone binaries for the API. File an issue on [aQute-os](https://github.com/aQute-os/v2Archive.osgi.enroute) for this.

**Comment by ghenzler** [comment]
Ok thanks @pkriens (now we ended up with a different approach though)
